# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.4.1
    hooks:
      - id: zimports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch # Both master and main are protected by default
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude_types: [ json ]
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: name-tests-test
        args: [ '--django' ]

#      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
        args: [ '--exclude', 'tla_cleanup_job_wrapper.py|nfs_volumemount_cleaner.py' ]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
